# Generated by Django 5.0.2 on 2024-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Railways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_move', models.IntegerField(default=-1)),
                ('second_move', models.IntegerField(default=-1)),
                ('third_move', models.IntegerField(default=-1)),
                ('fourth_move', models.IntegerField(default=-1)),
                ('fifth_move', models.IntegerField(default=-1)),
                ('sixth_move', models.IntegerField(default=-1)),
                ('seventh_move', models.IntegerField(default=-1)),
                ('eighth_move', models.IntegerField(default=-1)),
                ('ninth_move', models.IntegerField(default=-1)),
                ('tenth_move', models.IntegerField(default=-1)),
                ('eleventh_move', models.IntegerField(default=-1)),
                ('twelfth_move', models.IntegerField(default=-1)),
                ('thirteenth_move', models.IntegerField(default=-1)),
                ('fourteenth_move', models.IntegerField(default=-1)),
                ('fifteenth_move', models.IntegerField(default=-1)),
                ('sixteenth_move', models.IntegerField(default=-1)),
                ('seventeenth_move', models.IntegerField(default=-1)),
                ('eighteenth_move', models.IntegerField(default=-1)),
                ('nineteenth_move', models.IntegerField(default=-1)),
                ('twentieth_move', models.IntegerField(default=-1)),
                ('key', models.CharField(max_length=30)),
                ('B1', models.IntegerField(default=20)),
                ('B10', models.IntegerField(default=2)),
                ('B11', models.IntegerField(default=2)),
                ('B13', models.IntegerField(default=1)),
                ('B2', models.IntegerField(default=500000000)),
                ('B3', models.IntegerField(default=50000)),
                ('B4', models.IntegerField(default=50000)),
                ('B5', models.IntegerField(default=40)),
                ('B6', models.IntegerField(default=80)),
                ('B7', models.IntegerField(default=85)),
                ('B9', models.IntegerField(default=2)),
                ('D10', models.IntegerField(default=200)),
                ('D11', models.IntegerField(default=14)),
                ('D12', models.IntegerField(default=26)),
                ('D13', models.IntegerField(default=600)),
                ('G1', models.IntegerField(default=250)),
                ('G2', models.IntegerField(default=300)),
                ('a', models.IntegerField(default=0)),
                ('t', models.IntegerField(default=1)),
                ('tp', models.IntegerField(default=0)),
            ],
        ),
    ]
